name: Run Bot Cron Job

on:
  schedule:
    - cron: '0 * * * *'  # This will run the bot every hour
  workflow_dispatch:  # This allows you to trigger the workflow manually from the GitHub UI

jobs:
  run_bot:
    runs-on: ubuntu-latest  # You can change this if you want a different environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use the appropriate version of Python you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Make sure you have a requirements.txt in your repo

      - name: Run the bot
        run: |
          python bot.py  # Replace with your actual bot script name
