name: Run Python Bot

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python Bot
      run: |
        # Make sure to set the path to use Chromium
        export CHROMIUM_BIN="/usr/bin/chromium-browser"
        python mybot.py
