name: Run Bot Cron Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium requests

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Run bot
        run: python mybot.py
